spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/woniuticket?allowMultiQueries=true
    username: root
    password: root
  mvc:
    view:
      prefix: /
      suffix: .html
    
server:
  port: 80
  

logging:
  level:
     com.woniuxy.dao : debug
      
    
    
  

