spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.7.95:3306/woniuticket?allowMultiQueries=true&characterEncoding=utf8
    username: root
    password: java
  mvc:
    view:
      prefix: /
      suffix: .html
    
server:
  port: 80
  

logging:
  level:
     com.woniuxy.dao : debug
      
    
    
  

