spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
<<<<<<< HEAD
<<<<<<< HEAD
    url: jdbc:mysql://localhost:3306/woniuticket?allowMultiQueries=true
    username: root
    password: root
  mvc:
    view:
      prefix: /
      suffix: .html
    
server:
  port: 80
  

logging:
  level:
     com.woniuxy.dao : debug
      
    
    
  
=======
    url: jdbc:mysql://localhost:3306/woniuticket?characterEncoding=utf8
    username: root
    password: java
    
server:
  port: 80
>>>>>>> branch 'master' of git@github.com:zgx-rookie/woniuticket.git
=======
    url: jdbc:mysql://localhost:3306/woniuticket?characterEncoding=utf8
    username: root
    password: java
    
server:
  port: 80
>>>>>>> branch 'master' of git@github.com:zgx-rookie/woniuticket.git
